<?xml version="1.0"?>
<robot name="omnigrasper" xmlns:xacro="http://ros.org/wiki/xacro">

    <!-- Xacro macro for the arm -->
    <xacro:macro name="omnigrasper_arm">
        <link name="plate">
            <!-- <xacro:visuals_collisions_arm_0/> -->
            <visual>
                <geometry>
                    <box size="0.25 0.25 0.10"/>
                </geometry>
            </visual>
        </link>

        <joint name="plate_arm_0" type="fixed">
            <parent link="plate"/>
            <child link="arm_0"/>
            <origin xyz="0 0 0.141"/>
        </joint>
        <link name="arm_0">
            <!-- <xacro:visuals_collisions_arm_0/> -->
            <visual>
                <geometry>
                    <box size="0.05 0.05 0.05"/>
                </geometry>
            </visual>
        </link>

        <joint name="arm_0_1" type="revolute">
            <parent link="arm_0"/>
            <child link="arm_1"/>
            <!-- <limit effort="${5}" velocity="${5}" lower="${-M_PI}" upper="${M_PI}"/> -->
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <axis xyz="0 0 1"/>
            <!-- <dynamics damping="${joint_dmp}"/> -->
        </joint>
        <link name="arm_1">
            <!-- TODO Parts to add : frame adaptor FRP54-A110K, idler FRP54-I110 -->
            <xacro:box_vci name="arm_1" mass="0.855"
                size_x="0.054" size_y="0.132" size_z="0.054"
                xyz="0 0 0"/>
            <!-- <xacro:property name="arm_1_mass" value="0.855" />
            <xacro:property name="arm_1_lx" value="0.054" />
            <xacro:property name="arm_1_ly" value="0.132" />
            <xacro:property name="arm_1_lz" value="0.054" />
            <!-- <xacro:visuals_collisions_arm_1/> --
            <visual> <!-- H54-200-S500 --
                <geometry>
                    <box size="${arm_1_lx} ${arm_1_ly} ${arm_1_lz}"/>
                </geometry>
            </visual>
            <inertial> <!-- H54-200-S500 --
                <!-- center of mass --
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <mass value="${arm_1_mass}"/>
                <!-- box inertia: 1/12*m(y^2+z^2), ... --
                <inertia ixx="${1/12*arm_1_mass*(arm_1_ly**2 + arm_1_lz**2)}" ixy="0" ixz="0"
                    iyy="${1/12*arm_1_mass*(arm_1_lx**2 + arm_1_lz**2)}" iyz="0"
                    izz="${1/12*arm_1_mass*(arm_1_lx**2 + arm_1_ly**2)}"/>
            </inertial> -->
        </link>

        <joint name="arm_1_2" type="revolute">
            <parent link="arm_1"/>
            <child link="arm_2"/>
            <!-- <limit effort="${5}" velocity="${5}" lower="${-M_PI}" upper="${M_PI}"/> -->
            <origin rpy="${M_PI/2} ${-M_PI/2} 0" xyz="0 0 0"/>
            <axis xyz="0 0 1"/>
            <!-- <dynamics damping="${joint_dmp}"/> -->
        </joint>
        <link name="arm_2">
            <xacro:visuals_collisions_arm_2/>
            <!-- TODO Parts to add : modified (by us) frame FRP54-H220, modified
            (by us) frame adaptor FRP54-H120K (modified by us), idler FRP54-I110 -->
            <!-- <xacro:visuals_collisions_arm_2/> -->
            <xacro:box_vci name="profile_2" mass="${1.38*0.180}"
                size_x="0.180" size_y="0.040" size_z="0.040"
                xyz="${0.001*(51+180/2)} 0 0"/>
            <!-- <xacro:property name="profile_2_mass" value="${1.38*0.180}" />
            <xacro:property name="profile_2_lx" value="0.180" />
            <xacro:property name="profile_2_ly" value="0.040" />
            <xacro:property name="profile_2_lz" value="0.040" />
            <visual> <!-- aluminium profile --> -->
                <!-- <origin rpy="0 0 0" xyz="${0.001*(51+180/2)} 0 0"/>
                <geometry name="profile_2">
                    <box size="${profile_2_lx} ${profile_2_ly} ${profile_2_lz}"/>
                </geometry>
            </visual>
            <inertial> <!-- aluminium profile --> -->
                <!-- TODO: take the moments of inertia provided by manufacturer -->
                <!-- center of mass -->
                <!-- <origin rpy="0 0 0" xyz="${0.001*(51+180/2)} 0 0"/>
                <mass value="${profile_2_mass}"/> -->
                <!-- box inertia: 1/12*m(y^2+z^2), ... -->
                <!-- <inertia ixx="${1/12*profile_2_mass*(profile_2_ly**2 + profile_2_lz**2)}" ixy="0" ixz="0"
                    iyy="${1/12*profile_2_mass*(profile_2_lx**2 + profile_2_lz**2)}" iyz="0"
                    izz="${1/12*profile_2_mass*(profile_2_lx**2 + profile_2_ly**2)}"/>
            </inertial> -->

            <xacro:box_vci name="L54_50_S500" mass="0.662"
                size_x="0.054" size_y="0.054" size_z="0.114"
                xyz="${0.001*(51+180/2)} 0 0"/>
            <!-- <xacro:property name="L54_50_S500_mass" value="0.662" />
            <xacro:property name="L54_50_S500_lx" value="0.054" />
            <xacro:property name="L54_50_S500_ly" value="0.054" />
            <xacro:property name="L54_50_S500_lz" value="0.114" />
            <visual> <!-- L54-50-S500 --> -->
                <!-- <origin rpy="0 0 0" xyz="${0.001*(51+180+6+54/2)} 0 0"/>
                <geometry name="L54_50_S500"> <!-- L54-50-S500 --> -->
                    <!-- <box size="${L54_50_S500_lx} ${L54_50_S500_ly} ${L54_50_S500_lz}"/>
                </geometry>
            </visual>
            <inertial> <!-- L54-50-S500 --> -->
                <!-- center of mass -->
                <!-- <origin rpy="0 0 0" xyz="${0.001*(51+180+6+54/2)} 0 0"/>
                <mass value="${L54_50_S500_mass}"/> -->
                <!-- box inertia: 1/12*m(y^2+z^2), ... -->
                <!-- <inertia ixx="${1/12*L54_50_S500_mass*(L54_50_S500_ly**2 + L54_50_S500_lz**2)}" ixy="0" ixz="0"
                    iyy="${1/12*L54_50_S500_mass*(L54_50_S500_lx**2 + L54_50_S500_lz**2)}" iyz="0"
                    izz="${1/12*L54_50_S500_mass*(L54_50_S500_lx**2 + L54_50_S500_ly**2)}"/>
            </inertial> -->
        </link>

        <joint name="arm_0_1" type="revolute">
            <parent link="arm_0"/>
            <child link="arm_1"/>
            <!-- <limit effort="${joint_1_eff}" lower="${-joint_1_lim}" upper="${joint_1_lim}" velocity="${joint_vel}"/> -->
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <axis xyz="0 0 1"/>
            <!-- <dynamics damping="${joint_dmp}"/> -->
        </joint>
        <link name="arm_1">
            <xacro:visuals_collisions_arm_1/>
            <inertial>
                <!-- Parts to add : frame adaptor FRP54-A110K, idler FRP54-I110 -->
                <xacro:property name="arm_1_mass" value="0.855" />
                <xacro:property name="arm_1_lx" value="0.054" />
                <xacro:property name="arm_1_ly" value="0.132" />
                <xacro:property name="arm_1_lz" value="0.054" />
                <!-- center of mass -->
                <origin rpy="0 0 0" xyz="0 0 ${6+54/2}"/>
                <mass value="arm_1_mass"/>
                <!-- box inertia: 1/12*m(y^2+z^2), ... -->
                <inertia ixx="${1/12*arm_1_mass*(arm_1_ly**2 + arm_1_lz**2)}" ixy="0" ixz="0" iyy="${1/12*arm_1_mass*(arm_1_lx**2 + arm_1_lz**2)}" iyz="0" izz="${1/12*arm_1_mass*(arm_1_lx**2 + arm_1_ly**2)}"/>
            </inertial>
        </link>

        <joint name="arm_0_1" type="revolute">
            <parent link="arm_0"/>
            <child link="arm_1"/>
            <!-- <limit effort="${joint_1_eff}" lower="${-joint_1_lim}" upper="${joint_1_lim}" velocity="${joint_vel}"/> -->
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <axis xyz="0 0 1"/>
            <!-- <dynamics damping="${joint_dmp}"/> -->
        </joint>
        <link name="arm_1">
            <xacro:visuals_collisions_arm_1/>
            <inertial>
                <!-- Parts to add : frame adaptor FRP54-A110K, idler FRP54-I110 -->
                <xacro:property name="arm_1_mass" value="0.855" />
                <xacro:property name="arm_1_lx" value="0.054" />
                <xacro:property name="arm_1_ly" value="0.132" />
                <xacro:property name="arm_1_lz" value="0.054" />
                <!-- center of mass -->
                <origin rpy="0 0 0" xyz="0 0 ${6+54/2}"/>
                <mass value="arm_1_mass"/>
                <!-- box inertia: 1/12*m(y^2+z^2), ... -->
                <inertia ixx="${1/12*arm_1_mass*(arm_1_ly**2 + arm_1_lz**2)}" ixy="0" ixz="0" iyy="${1/12*arm_1_mass*(arm_1_lx**2 + arm_1_lz**2)}" iyz="0" izz="${1/12*arm_1_mass*(arm_1_lx**2 + arm_1_ly**2)}"/>
            </inertial>
        </link>

        <joint name="leg_${index}_2_3" type="revolute">
            <parent link="leg_${index}_2"/>
            <child link="leg_${index}_3"/>
            <limit effort="${joint_eff}" lower="${-joint_lim}" upper="${joint_lim}" velocity="${joint_vel}"/>
            <origin rpy="0 0 0" xyz="0 ${arm_1_length} 0"/>
            <axis xyz="-1 0 0"/>
            <dynamics damping="${joint_dmp}"/>
        </joint>
        <link name="leg_${index}_3">
            <xacro:visuals_collisions_leg_3/>
            <inertial>
                <!-- CENTER OF MASS -->
                <origin rpy="${PI_2} 0 0" xyz="0 ${leg3_length/2} 0"/>
                <mass value="${leg3_mass}"/>
                <!-- box inertia: 1/12*m(y^2+z^2), ... -->
                <inertia ixx="${1/12*leg3_mass*(leg3_width*leg3_width+leg3_length*leg3_length)}" ixy="0" ixz="0" iyy="${1/12*leg3_mass*(leg3_width*leg3_width+leg3_length*leg3_length)}" iyz="0" izz="${1/12*leg3_mass*(2*leg3_width*leg3_width)}"/>
            </inertial>
        </link>
        <joint name="force_sensor_${index}_fix" type="fixed">
            <parent link="leg_${index}_3"/>
            <child link="force_sensor_${index}"/>
            <origin rpy="${PI} 0 ${PI_2}" xyz="0 ${force_y_offset} -${force_z_offset}"/>
        </joint>
        <link name="force_sensor_${index}"/>

        <!-- Description used by our Dart simulator -->
        <dart_sensor type="force">
          <link>force_sensor_${index}</link>
          <frequency>1000</frequency>
          <topic>optoforce_${index}</topic>
        </dart_sensor>
        <transmission name="tran${index}1">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="body_leg_${index}">
                <hardwareInterface>PositionJointInterface</hardwareInterface>
            </joint>
            <actuator name="motor${index}1">
                <hardwareInterface>PositionJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>
        <transmission name="tran${index}2">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="arm_1_2">
                <hardwareInterface>PositionJointInterface</hardwareInterface>
            </joint>
            <actuator name="motor${index}2">
                <hardwareInterface>PositionJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>
        <transmission name="tran${index}3">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="leg_${index}_2_3">
                <hardwareInterface>PositionJointInterface</hardwareInterface>
            </joint>
            <actuator name="motor${index}2">
                <hardwareInterface>PositionJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>
    </xacro:macro>
    <!-- end of arm links/joints -->
</robot>
