# This file is a part of the ERC ResiBots project.
#
# This software is governed by the CeCILL license under French law and abiding by
# the rules of distribution of free software. You can use, modify and/ or redistribute
# the software under the terms of the CeCILL license as circulated by CEA, CNRS
# and INRIA at the following URL "http://www.cecill.info". As a counterpart to the
# access to the source code and rights to copy, modify and redistribute granted by
# the license, users are provided only with a limited warranty and the software's
# author, the holder of the economic rights, and the successive licensors have only
# limited liability. In this respect, the user's attention is drawn to the risks
# associated with loading, using, modifying and/or developing or reproducing the
# software by the user in light of its specific status of free software, that may
# mean that it is complicated to manipulate, and that also therefore means that it
# is reserved for developers and experienced professionals having in-depth computer
# knowledge. Users are therefore encouraged to load and test the software's
# suitability as regards their requirements in conditions enabling the security of
# their systems and/or data to be ensured and, more generally, to use and operate
# it in the same conditions as regards security. The fact that you are presently
# reading this means that you have had knowledge of the CeCILL license and that
# you accept its terms.


dynamixel_control:
  # loop_frequency: do not reduce it as then it will not be as reactive to the safety constraints
  loop_frequency: 100
  cycle_time_error_threshold: 0.05
  serial_interface: /dev/ttyUSB0
  baudrate: 1000000 # in bauds
  read_timeout: 0.02 # in seconds
  scan_timeout: 0.02
  # correspondance between hardware IDs of the actuators and their names in ROS
  servos:
    arm_0_1:
      id: 1
      max_speed: 0.2
      offset: 3.14159265359
    arm_1_2:
      id: 2
      max_speed: 0.2
      offset: 3.14159265359
    arm_2_3:
      id: 3
      max_speed: 0.2
      offset: 3.14159265359
    arm_3_4:
      id: 4
      max_speed: 0.2
      offset: 3.14159265359
    arm_4_5:
      id: 5
      max_speed: 0.2
      offset: 3.14159265359

dynamixel_controllers:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  omni_arm_controller: # Safety limits for some controllers used with the arm
    min_heights:
      - # height limit to protect the arm and the mobile base from each other
        x_min: -0.28
        y_min: -0.40
        x_max: 0.99
        y_max: 0.15
          # x_min: -0.18
          # y_min: -0.30
          # x_max: 0.50
          # y_max: 0.30
        # hard_min_height: 0.15
        # soft_min_height: 0.20
        hard_min_height: 0.20
        soft_min_height: 0.25
      - # the general height limit, applies everywhere
        # hard_min_height: -0.16
        # soft_min_height: -0.07
        hard_min_height: -0.12
        soft_min_height: -0.04
        # hard_min_height: 0.20
        # soft_min_height: 0.25

  # x_min y_min etc decides the dimensions of the box, when inside this box, the servos are taken care to not violate the soft limit values.
  # at the moment, the box is given a high x value to allow all servos to be inside the box all the time. Later, care must be taken to smallen this box
  # to fit only the base and give more freedom to the arm . note that the end effector is lower than the current last joint seen in the arm, so the arm stops even before
